config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000


  resources :projects do
    member do
      get 'submit' => 'projects#submit'
      get 'withdraw' => 'projects#withdraw'
    end
  end

  resources :users,
    only: [:new, :create],
    path_names: { new: "signup"}

  get 'my_investments' => 'investments#my_investments'
  get 'my_projects' => 'projects#my_projects'
  get 'verification/:token', to: 'users#verify', as: 'verify_email'

  resources :investments do
    member do
      get 'invest' => 'investments#invest'
      get 'divest' => 'investments#divest'
    end
  end

  root 'welcome#index'
  get 'about' => 'about#index'
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'business_canvas' => 'about#business_canvas'
  get 'team' => 'about#team'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/investment.rb
class Investment < ActiveRecord::Base

  validates :minimum_order, numericality: {
    greater_than: 999.99
  }

  belongs_to :user

  def self.per_page
    10
  end

  def self.seed_data!
    7.times do |number|
      interest_rate = 1.50 + (0.50 * number)
      maturity_date = number.years.from_now
      issue_date = Date.today
      offer_end_period = 3.months.from_now
      Investment.create(
        :term => number + 1,
        :interest_rate => interest_rate,
        :minimum_order => 1_000,
        :denomination => 1_000,
        :maturity_date => maturity_date,
        :issue_date => issue_date,
        :offer_start_period => issue_date,
        :offer_end_period => offer_end_period
      )
    end
  end
end

app/controllers/investments_controller.rb
class InvestmentsController < ApplicationController
  include ActionView::Helpers::NumberHelper

  load_and_authorize_resource
  before_action :set_investment, only: [:show, :edit, :update, :destroy, :invest, :divest]

  def invest
    if current_user
      current_user.investments << @investment
      redirect_to investments_path, notice: "#{@investment.term} Year #{number_to_percentage(@investment.interest_rate, precision: 2)}  has been moved to your inventory."
    end
  end

  def divest
    @investment.user = nil
    @investment.save
      redirect_to my_investments_path, notice: "#{@investment.term} #{@investment.interest_rate} has been sold!."
    end

  def index
    @investments = Investment.where(user_id: nil).paginate(page: params[:page], per_page: 20)
  end

  def my_investments
    @investments = Investment.where(user_id: current_user.id).paginate(page: params[:page], per_page: 20)
    render 'investments/index'
  end

  def show
  end

  def new
    @investment = Investment.new
  end

  def edit
  end

  def create
    @investment = Investment.new(investment_params)
    creation_message = "#{@investment.term} year #{@investment.interest_rate}% rate was successfully created."
    respond_to do |format|
      if @investment.save
        format.html { redirect_to @investment, notice: creation_message }
        format.json { render :show, status: :created, location: @investment }
      else
        format.html { render :new }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /investments/1
  # PATCH/PUT /investments/1.json
  def update
    respond_to do |format|
      update_message = "#{@investment.term} year #{@investment.interest_rate}% rate was successfully updated."

      if @investment.update(investment_params)
        format.html { redirect_to @investment, notice: update_message }
        format.json { render :show, status: :ok, location: @investment }
      else
        format.html { render :edit }
        format.json { render json: @investment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /investments/1
  # DELETE /investments/1.json
  def destroy
    destroy_message = "#{@investment.term} year #{@investment.interest_rate} was successfully destroyed."

    @investment.destroy
    respond_to do |format|
      format.html { redirect_to investments_path, notice: destroy_message }
      format.json { head :no_content }
    end
  end



  private
  # Use callbacks to share common setup or constraints between actions.
  def set_investment
    @investment = Investment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def investment_params
    params.require(:investment).permit(:term, :interest_rate, :minimum_order, :denomination, :maturity_date, :issue_date, :offer_start_period, :offer_end_period)
  end
end

app/helpers/investments_helper.rb
module InvestmentsHelper
end

app/views/investments/_form.html.erb
<%= form_for(@investment) do |f| %>
  <% if @investment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@investment.errors.count, "error") %> prohibited this investment from being saved:</h2>

      <ul>
      <% @investment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :term %><br>
    <%= f.number_field :term %>
  </div>
  <div class="field">
    <%= f.label :interest_rate %><br>
    <%= f.text_field :interest_rate %>
  </div>
  <div class="field">
    <%= f.label :minimum_order %><br>
    <%= f.number_field :minimum_order %>
  </div>
  <div class="field">
    <%= f.label :denomination %><br>
    <%= f.number_field :denomination %>
  </div>
  <div class="field">
    <%= f.label :maturity_date %><br>
    <%# f.date_select :maturity_date %>
    <%= f.text_field :maturity_date %>
  </div>
  <div class="field">
    <%= f.label :issue_date %><br>
    <%# f.date_select :issue_date %>
    <%= f.text_field :issue_date %>
  </div>
  <div class="field">
    <%= f.label :offer_start_period %><br>
    <%# f.date_select :offer_start_period %>
    <%= f.text_field :offer_start_period %>
  </div>
  <div class="field">
    <%= f.label :offer_end_period %><br>
    <%# f.date_select :offer_end_period %>
    <%= f.text_field :offer_end_period %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/investments/edit.html.erb
<h1>Editing investment</h1>

<%= render 'form' %>

<%= link_to 'Show', @investment %> |
<%= link_to 'Back', investments_path %>

app/views/investments/index.html.erb
<h1>GET INVESTED!</h1>
<%= image_tag("wateringplant.jpg", size: "618x343", :alt => "rss feed") %>
<% if current_user.investor? || current_user.admin? || current_user.manager? %>

<% else %>
  <h3>Renewable Yield loans money to small residential solar
    providers to fund their projects and then takes those loans
    and breaks the cash flow into various tranches differentiated
    by term and interest rate.</h3>
  <h3>
    Investors will be receive a diversified pro rata cash flow
    share of all of the loans outstanding at the time of issue
    rather than the cash flow of just one particular solar project.
  </h3>
<% end %>
<table>
  <thead>
  <tr>
    <th>Term</th>
    <th>Interest rate</th>
    <th>Minimum order</th>
    <th>Denomination</th>
    <th>Maturity date</th>
    <th>Offer end period</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= content_tag_for(:tr, @investments) do |investment| %>
    <td><%= investment.term %> Year</td>
    <td><%= number_to_percentage(investment.interest_rate, precision: 2) %></td>
    <td><%= number_to_currency(investment.minimum_order, precision: 2) %></td>
    <td><%= number_to_currency(investment.denomination, precision: 2) %></td>
    <td><%= investment.maturity_date.strftime('%B %-d, %Y') %></td>
    <td><%# investment.issue_date %></td>
    <td><%# investment.offer_start_period %></td>
    <td><%= investment.offer_end_period.strftime('%B %-d, %Y') %></td>
    <td><%= link_to 'Show', investment %></td>
    <% if current_user %>
      <% if can? :update, investment %>
        <td><%= link_to 'Edit', edit_investment_path(investment) %></td>
      <% end %>
      <% if can? :has_money, investment %>
        <td>
          <% if current_user.investments.include?(investment) %>
            <%= link_to 'Divest', divest_investment_path(investment) %></td>
          <% else %>
            <%= link_to 'Invest', invest_investment_path(investment) %></td>
          <% end %>
      <% end %>
      <% if can? :destroy, investment %>
        <td><%= link_to 'Destroy', investment, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>
<%= will_paginate @investments %>

<br>
<% if can? :create, @investment %>
  <%= link_to 'New Investment', new_investment_path %>
<% end %>
<br>
<%= link_to 'Home', root_path %>
<br>
<%= link_to 'About', about_path %>

app/views/investments/new.html.erb
<h1>New investment</h1>

<%= render 'form' %>

<%= link_to 'Back', investments_path %>

app/views/investments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>RENYD <%= @investment.issue_date.strftime('%Y') %>-1/
    <%= @investment.term %> are unsecured bonds issued by Renewable
    Yield. The bonds have a <%= @investment.term %> year term with
    a <%= number_to_percentage(@investment.interest_rate, precision: 2) %>
    interest rate. The bonds will mature on
    <%= @investment.maturity_date.strftime('%B %-d, %Y') %> which is
    <%= @investment.term %> years after their offer date of
    <%= @investment.issue_date.strftime('%B %-d, %Y') %>.
  </strong>
</p>

<p>
  <strong>The minimum order is <%= number_to_currency(@investment.minimum_order, precision: 2) %> and
    increments are <%= number_to_currency(@investment.denomination, precision: 2) %>.
  </strong>
</p>

<p>
  <strong>The offering period for this bond started on
    <%= @investment.offer_start_period.strftime('%B %-d, %Y') %> and will end on
    <%= @investment.offer_end_period.strftime('%B %-d, %Y') %>.
  </strong>
</p>

<% if current_user %>
  <% if can? :update, @investment %>
    <%= link_to 'Edit', edit_investment_path(@investment) %>
  <% end %>
  <% if can? :has_money, @investment %>
    <% if current_user.investments.include?(@investment) %>
      <%= "If you need to divest, click" %>
      <%= link_to 'Divest', divest_investment_path(@investment) %>
      <br>
    <% else %>
      <%= "If you want to invest, click" %>
      <%= link_to 'Invest', invest_investment_path(@investment) %>
      <br>
    <% end %>
    <%= link_to 'Back', my_investments_path %>
  <% end %>
<% else %>
  <br>
  <%= link_to 'Back', :back %>
<% end %>
<br>
<%= link_to 'Home', root_path %>
<br>
<%= link_to 'About', about_path %>