config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000


  resources :projects do
    member do
      get 'submit' => 'projects#submit'
      get 'withdraw' => 'projects#withdraw'
    end
  end

  resources :users,
    only: [:new, :create],
    path_names: { new: "signup"}

  get 'my_investments' => 'investments#my_investments'
  get 'my_projects' => 'projects#my_projects'
  get 'verification/:token', to: 'users#verify', as: 'verify_email'

  resources :investments do
    member do
      get 'invest' => 'investments#invest'
      get 'divest' => 'investments#divest'
    end
  end

  root 'welcome#index'
  get 'about' => 'about#index'
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'business_canvas' => 'about#business_canvas'
  get 'team' => 'about#team'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end
end

app/views/welcome/index.html.erb
<h1>Renewable Yield</h1>
<%= image_tag("globe_energy.jpg", size: "618x323",:alt => "rss feed") %>
<h3>Someday renewable energy will just be known as energy. Our intention is to be a part of making that happen while
  earning a return for investors.</h3>

<h4>The are many kinds of renewable energy - solar, wind, tidal and geothermic are examples but we will focus initially on the residential solar market.  That market and the residential projects in which we would be investing are a part of the largest, most mature, most diverse and most commoditized of the renewable energy markets.  If you are interested in submiting a residential solar project that needs an investor, please signup and <%= link_to 'GET FUNDED!', projects_path %> </h4>
<h4>Interest rates have been low for a long time.  You have the opportunity to invest in certificate of deposit equivalents and beat bank rates by at least 0.50%.  If that sounds good to you in addition to knowing that you would be funding solar project, please signup and <%= link_to 'GET INVESTED!', investments_path %></h4>

<br>
<%= link_to 'Home', root_path %>
<br>
<%= link_to 'About', about_path %>