config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'localhost', port: 3000


  resources :projects do
    member do
      get 'submit' => 'projects#submit'
      get 'withdraw' => 'projects#withdraw'
    end
  end

  resources :users,
    only: [:new, :create],
    path_names: { new: "signup"}

  get 'my_investments' => 'investments#my_investments'
  get 'my_projects' => 'projects#my_projects'
  get 'verification/:token', to: 'users#verify', as: 'verify_email'

  resources :investments do
    member do
      get 'invest' => 'investments#invest'
      get 'divest' => 'investments#divest'
    end
  end

  root 'welcome#index'
  get 'about' => 'about#index'
  get 'login' => 'sessions#login'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'business_canvas' => 'about#business_canvas'
  get 'team' => 'about#team'
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
  # request = open('http://developer.nrel.gov/api/pvwatts/v5.json?api_key=mOwXKaie0UZB8tihBfZj5b2YpYkETjc33Yl5J1EM&lat=40&lon=-105&system_capacity=4&azimuth=180&tilt=40&array_type=1&module_type=1&losses=10')
  belongs_to :user
  # has_one :nrel_data

  # app/models/nrel_data.rb
  # class NrelData < AR::Base
  #   belongs_to :user
  # end

  def self.per_page
    5
  end

  def self.seed_data!
    20.times do |number|
      user_id = 11 + (number/10)
      Project.create(
      :format => ['json', 'xml'].sample,
      :api_key => Faker::Internet.password,
      :system_capacity => rand(1..10),
      :module_type => rand(0..2),
      :losses => rand(-5..99),
      :array_type => rand(0..4),
      :tilt => rand(0..99),
      :azimuth => rand(0..360),
      :address => "#{Faker::Address.street_address}, #{Faker::Address.city}, #{Faker::Address.state_abbr}  #{Faker::Address.zip}",
      :lat => Faker::Address.latitude.to_f.round(12),
      :lon => Faker::Address.longitude.to_f.round(12),
      :file_id => 94018,
      :dataset => ['tmy2', 'tmy3', 'intl'].sample,
      :radius => 100,
      :timeframe => 'monthly',
      :dc_ac_ratio => 1.1,
      :gcr => rand(0..3),
      :inv_eff => rand(90..99.5),
      :callback => 'JSON',
      :npv => rand(-20_000..20_000),
      :irr => rand(-5..10),
      :project_score => rand(0..100),
      :status => ['Funded', 'Not Funded'].sample,
      :user_id => user_id
      )
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ActionView::Helpers::NumberHelper

  load_and_authorize_resource
  before_action :set_project, only: [:show, :edit, :update, :destroy, :submit, :withdraw]

  # def submit
  #   if current_user
  #     current_user.projects << @project
  #     redirect_to projects_path, notice: "#{@project.term} #{@project.interest_rate} has been moved to your inventory."
  #   end
  # end

  # def withdraw
  #   @project.user = nil
  #   @project.save
  #   redirect_to my_projects_path, notice: "#{@project.term} #{@project.interest_rate} has been sold!."
  # end

  def index
    @projects = Project.all.paginate(page: params[:page])
    @projects_count = Project.where(:status => 'Funded').count
    @projects_value = number_to_currency(@projects_count * 20_000, precision: 2)
  end

  def my_projects
    @projects = Project.where(user_id: current_user.id).paginate(page: params[:page], per_page: 20)
    render 'projects/index'
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    #@project.nrel_data.build
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "#{@project.system_capacity} Kw project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "#{@project.system_capacity} Kw project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    destroy_message = "#{@project.system_capacity} Kw project has been destroyed!"
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: destroy_message }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(
        :system_capacity, :module_type, :losses, :array_type,
        :tilt, :azimuth, :address, :lat, :lon)  #:format, :api_key,, :file_id, :dataset, :radius, :timeframe, :dc_ac_ratio, :gcr, :inv_eff, :callback, :npv, :irr, :project_score, :status
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% @project.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% if current_user.admin? || current_user.admin? %>

      <%= f.label :format %>
      <br>
      <%= f.text_field :format %>
      </div>
      <div class="field">
        <%= f.label :api_key %>
        <br>
        <%= f.text_field :api_key %>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :system_capacity %>
      <br>
      <%= f.text_field :system_capacity %>
    </div>
    <div class="field">
      <%= f.label :module_type %>
      <br>
      <%= f.number_field :module_type %>
    </div>
    <div class="field">
      <%= f.label :losses %>
      <br>
      <%= f.text_field :losses %>
    </div>
    <div class="field">
      <%= f.label :array_type %>
      <br>
      <%= f.number_field :array_type %>
    </div>
    <div class="field">
      <%= f.label :tilt %>
      <br>
      <%= f.text_field :tilt %>
    </div>
    <div class="field">
      <%= f.label :azimuth %>
      <br>
      <%= f.text_field :azimuth %>
    </div>
    <div class="field">
      <%= f.label :address %>
      <br>
      <%= f.text_field :address %>
    </div>
    <div class="field">
      <%= f.label :lat %>
      <br>
      <%= f.text_field :lat %>
    </div>
    <div class="field">
      <%= f.label :lon %>
      <br>
      <%= f.text_field :lon %>
    </div>
    <% if current_user.admin? || current_user.admin? %>

      <div class="field">
        <%= f.label :file_id %>
        <br>
        <%= f.text_field :file_id %>
      </div>
      <div class="field">
        <%= f.label :dataset %>
        <br>
        <%= f.text_field :dataset %>
      </div>
      <div class="field">
        <%= f.label :radius %>
        <br>
        <%= f.number_field :radius %>
      </div>
      <div class="field">
        <%= f.label :timeframe %>
        <br>
        <%= f.text_field :timeframe %>
      </div>
      <div class="field">
        <%= f.label :dc_ac_ratio %>
        <br>
        <%= f.text_field :dc_ac_ratio %>
      </div>
      <div class="field">
        <%= f.label :gcr %>
        <br>
        <%= f.text_field :gcr %>
      </div>
      <div class="field">
        <%= f.label :inv_eff %>
        <br>
        <%= f.text_field :inv_eff %>
      </div>
      <div class="field">
        <%= f.label :callback %>
        <br>
        <%= f.text_field :callback %>
      </div>
      <div class="field">
        <%= f.label :npv %>
        <br>
        <%= f.number_field :npv %>
      </div>
      <div class="field">
        <%= f.label :irr %>
        <br>
        <%= f.text_field :irr %>
      </div>
      <div class="field">
        <%= f.label :project_score %>
        <br>
        <%= f.number_field :project_score %>
      </div>
      <div class="field">
        <%= f.label :status %>
        <br>
        <%= f.text_field :status %>
      </div>
    <% end %>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/projects/_non_provider.html.erb
<h3>Renewable Yield is proud to finance solar projects for small
  residential solar providers. If you fall into this category,
  please sign up as a provider and submit as many projects as you
  need. The more detail you can provide, the more accurately we
  can analyze your proposal. </h3>
<h3>Once submitted, we run it through NREL's
  PV Watts model to calculate potential energy generation, gather the
  applicable tax incentives from the DSIRE database, run our own
  numbers and give the project a score. The higher the score, the better
  chance of that project getting funded.
  You will be able to see what you have submitted, which, if any,
  of your project have been funded and which have not. You will not
  have access to other provider's projects.</h3>

app/views/projects/_provider.html.erb
<h2> If you want to submit a project click here => <%= link_to 'New Project', new_project_path %> </h2>
<table>
  <thead>
  <tr>
    <th>System capacity</th>
    <th>Address</th>
    <th>Lat</th>
    <th>Lon</th>
    <th>Npv</th>
    <th>Irr</th>
    <th>Project score</th>
    <th>Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= content_tag_for(:tr, @projects) do |project| %>
    <td><%= project.system_capacity %> kW</td>
    <td><%= project.address.byteslice(project.address.length - project.address.reverse.index(',') + 1, 2) %></td>
    <td><%= BigDecimal(project.lat).round(2) %></td>
    <td><%= BigDecimal(project.lon).round(2) %></td>
    <td><%= number_to_currency(project.npv, precision: 0) %></td>
    <td><%= number_to_percentage(project.irr, precision: 2) %></td>
    <td><%= project.project_score %></td>
    <td><%= project.status %></td>
    <% if current_user %>
      <% if can? :manage, project %>
        <td>
          <% if current_user.projects.include?(project) || current_user.admin? %>
            <%= link_to 'Show', project %>
            <% if project.status == 'Not Funded' || current_user.admin? || current_user.manager? %>
              <%= link_to 'Edit', edit_project_path(project) %>
              <%= link_to 'Destroy', project, method: :delete, data: {confirm: 'Are you sure?'} %>
            <% end %>
            </td>
          <% else %>
          <% end %>
      <% end %>
    <% end %>
  <% end %>
  </tbody>
</table>
<%= will_paginate @projects %>
<br>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<br>
<h1>GET FUNDED!</h1>
<%= image_tag("solar_panels.jpg", size: "618x343", :alt => "rss feed") %>

<h2>We have funded <%= @projects_count %> projects for a total of <%= @projects_value %> to date.</h2>

<% if current_user.provider? || current_user.admin? || current_user.manager? %>
  <%= render 'provider' %>
<% else %>
  <%= render 'non_provider' %>
<% end %>
<br>
<%= link_to 'Home', root_path %>
<br>
<%= link_to 'About', about_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Format:</strong>
  <%= @project.format %>
</p>

<p>
  <strong>Api key:</strong>
  <%= @project.api_key %>
</p>

<p>
  <strong>System capacity:</strong>
  <%= @project.system_capacity %>
</p>

<p>
  <strong>Module type:</strong>
  <%= @project.module_type %>
</p>

<p>
  <strong>Losses:</strong>
  <%= @project.losses %>
</p>

<p>
  <strong>Array type:</strong>
  <%= @project.array_type %>
</p>

<p>
  <strong>Tilt:</strong>
  <%= @project.tilt %>
</p>

<p>
  <strong>Azimuth:</strong>
  <%= @project.azimuth %>
</p>

<p>
  <strong>Address:</strong>
  <%= @project.address %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @project.lat %>
</p>

<p>
  <strong>Lon:</strong>
  <%= @project.lon %>
</p>

<p>
  <strong>File id:</strong>
  <%= @project.file_id %>
</p>

<p>
  <strong>Dataset:</strong>
  <%= @project.dataset %>
</p>

<p>
  <strong>Radius:</strong>
  <%= @project.radius %>
</p>

<p>
  <strong>Timeframe:</strong>
  <%= @project.timeframe %>
</p>

<p>
  <strong>Dc ac ratio:</strong>
  <%= @project.dc_ac_ratio %>
</p>

<p>
  <strong>Gcr:</strong>
  <%= @project.gcr %>
</p>

<p>
  <strong>Inv eff:</strong>
  <%= @project.inv_eff %>
</p>

<p>
  <strong>Callback:</strong>
  <%= @project.callback %>
</p>

<p>
  <strong>Npv:</strong>
  <%= @project.npv %>
</p>

<p>
  <strong>Irr:</strong>
  <%= @project.irr %>
</p>

<p>
  <strong>Project score:</strong>
  <%= @project.project_score %>
</p>

<p>
  <strong>Status:</strong>
  <%= @project.status %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>